"""Port of Group3r/Options/AssessmentOptions/PrivRights.cs

The C# body is `AssessmentOptions.LoadPrivRights()` on the partial class; here
it is a module-level loader that `AssessmentOptions.load_priv_rights()` calls.
Every description string is copied verbatim from the C# source, typos included.
"""

from group3rpy.options.assessment_options import PrivRightOption


def load_priv_rights() -> list[PrivRightOption]:
    # TODO : Reference https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-rights-assignment
    # to make these nicer for users
    return [
        PrivRightOption(
            priv_right_name="SeTakeOwnershipPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=True,
            local_privesc_desc="Can be used to grant yourself ownership on any file, registry key, etc.",
            ms_description="Take ownership of files or other objects",
        ),
        PrivRightOption(
            priv_right_name="SeSyncAgentPrivilege",
            grants_remote_access=True,
            remote_access_desc="",
            local_privesc=True,
            local_privesc_desc="",
            ms_description="Synchronize directory service data",
        ),
        PrivRightOption(
            priv_right_name="SeShutdownPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Shut down the system",
        ),
        PrivRightOption(
            priv_right_name="SeRelabelPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=True,
            local_privesc_desc="",
            ms_description="",
        ),
        PrivRightOption(
            priv_right_name="SeRestorePrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=True,
            local_privesc_desc="Can be used to overwrite/modify any file.",
            ms_description="Restore files and directories",
        ),
        PrivRightOption(
            priv_right_name="SeTrustedCredManAccessPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=True,
            local_privesc_desc="Microsoft provides the following additional detail: If an account is given this user right, the user of the account may create an application that calls into Credential Manager and is returned the credentials for another user.",
            ms_description="Access Credential Manager as a trusted caller",
        ),
        PrivRightOption(
            priv_right_name="SeNetworkLogonRight",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Access this computer from the network",
        ),
        PrivRightOption(
            priv_right_name="SeTcbPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=True,
            local_privesc_desc="Lets you impersonate any other user.",
            ms_description="Act as part of the operating system",
        ),
        PrivRightOption(
            priv_right_name="SeAssignPrimaryTokenPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=True,
            local_privesc_desc="Lets you impersonate accounts (after some backflips) look at the various 'potato' attacks, i.e. Rotten, Juicy, etc.",
            ms_description="Replace a process level token",
        ),
        PrivRightOption(
            priv_right_name="SeUndockPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Remove computer from docking station",
        ),
        PrivRightOption(
            priv_right_name="SeSystemProfilePrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Profile system performance",
        ),
        PrivRightOption(
            priv_right_name="SeProfileSingleProcessPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Profile single process",
        ),
        PrivRightOption(
            priv_right_name="SeMachineAccountPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Add workstations to domain - l0ss note: This can be leveraged as one part of that Resource Based Constrained Delegation kerberos backflip attack.",
        ),
        PrivRightOption(
            priv_right_name="SeRemoteInteractiveLogonRight",
            grants_remote_access=True,
            remote_access_desc="It's RDP. Good old RDP.",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Allow log on through Remote Desktop Services",
        ),
        PrivRightOption(
            priv_right_name="SeIncreaseQuotaPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Adjust memory quotas for a process",
        ),
        PrivRightOption(
            priv_right_name="SeInteractiveLogonRight",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Allow log on locally",
        ),
        PrivRightOption(
            priv_right_name="SeBackupPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=True,
            local_privesc_desc="Lets you override file and directory permissions to read any file on the FS.",
            ms_description="Back up files and directories",
        ),
        PrivRightOption(
            priv_right_name="SeChangeNotifyPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Bypass traverse checking",
        ),
        PrivRightOption(
            priv_right_name="SeSystemtimePrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Change the system time",
        ),
        PrivRightOption(
            priv_right_name="SeCreatePagefilePrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Create a pagefile",
        ),
        PrivRightOption(
            priv_right_name="SeCreateTokenPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=True,
            local_privesc_desc="Lets you grant yourself any access you want. Locally.",
            ms_description="Create a token object",
        ),
        PrivRightOption(
            priv_right_name="SeCreateGlobalPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Create global objects",
        ),
        PrivRightOption(
            priv_right_name="SeCreatePermanentPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Create permanent shared objects",
        ),
        PrivRightOption(
            priv_right_name="SeCreateSymbolicLinkPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=True,
            local_privesc_desc="",
            ms_description="Create symbolic links",
        ),
        PrivRightOption(
            priv_right_name="SeDebugPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=True,
            local_privesc_desc="Lets you do the mimikatz thing, you know, dump lsass.exe, cool stuff like that.",
            ms_description="Debug programs",
        ),
        PrivRightOption(
            priv_right_name="SeDenyNetworkLogonRight",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Deny access to this computer from the network",
        ),
        PrivRightOption(
            priv_right_name="SeDenyBatchLogonRight",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Deny log on as a batch job",
        ),
        PrivRightOption(
            priv_right_name="SeDenyServiceLogonRight",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Deny log on as a service",
        ),
        PrivRightOption(
            priv_right_name="SeDenyInteractiveLogonRight",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Deny log on locally",
        ),
        PrivRightOption(
            priv_right_name="SeDenyRemoteInteractiveLogonRight",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Deny log on through Remote Desktop Services",
        ),
        PrivRightOption(
            priv_right_name="SeRemoteShutdownPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Force shutdown from a remote system",
        ),
        PrivRightOption(
            priv_right_name="SeAuditPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Generate security audits",
        ),
        PrivRightOption(
            priv_right_name="SeImpersonatePrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=True,
            local_privesc_desc="Lets you impersonate accounts (after some backflips) look at the various 'potato' attacks, i.e. Rotten, Juicy, etc.",
            ms_description="Impersonate a client after authentication",
        ),
        PrivRightOption(
            priv_right_name="SeIncreaseWorkingSetPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Increase a process working set",
        ),
        PrivRightOption(
            priv_right_name="SeIncreaseBasePriorityPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Increase scheduling priority",
        ),
        PrivRightOption(
            priv_right_name="SeLoadDriverPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=True,
            local_privesc_desc="Lets you load device drivers. Privesc in this case is usually going to mean loading a known-vulnerable driver and then exploiting the known vulnerability.",
            ms_description="Load and unload device drivers",
        ),
        PrivRightOption(
            priv_right_name="SeLockMemoryPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Lock pages in memory",
        ),
        PrivRightOption(
            priv_right_name="SeBatchLogonRight",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Log on as a batch job",
        ),
        PrivRightOption(
            priv_right_name="SeServiceLogonRight",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Log on as a service",
        ),
        PrivRightOption(
            priv_right_name="SeSecurityPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Manage auditing and security log",
        ),
        PrivRightOption(
            priv_right_name="SeSystemEnvironmentPrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Modify firmware environment values",
        ),
        PrivRightOption(
            priv_right_name="SeManageVolumePrivilege",
            grants_remote_access=False,
            remote_access_desc="",
            local_privesc=False,
            local_privesc_desc="",
            ms_description="Perform volume maintenance tasks",
        ),
    ]
